spring.application.name=order-processing-users

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# user props
orders.demo.users.page-size=50
orders.demo.users.max-page-size=50
orders.demo.users.default-sort-attribute=username

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
