INSERT INTO orders.products (id, sku, "name", description, active, amount, currency, external_id)
VALUES
(nextval('orders.product_id_seq'::regclass), 'SKU-100001', 'Logitech MX Master 3S Mouse', 'Wireless performance mouse, 8K DPI sensor, USB-C charging', true, 99.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100002', 'Logitech K380 Keyboard', 'Compact multi-device Bluetooth keyboard', true, 39.90, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100003', 'Dell 24" Monitor SE2422H', '24-inch Full HD LED monitor, HDMI/VGA', true, 149.50, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100004', 'HP LaserJet Pro M404dn', 'Monochrome laser printer with duplex printing', true, 329.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100005', 'Brother HL-L2350DW Toner TN-760', 'High-yield black toner cartridge', true, 89.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100006', 'Samsung 970 EVO Plus 1TB SSD', 'NVMe M.2 internal solid state drive', true, 109.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100007', 'Kingston 16GB DDR4 3200MHz RAM', 'Desktop memory module CL16', true, 54.75, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100008', 'Seagate Barracuda 2TB HDD', '3.5-inch SATA internal hard drive', true, 62.40, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100009', 'Western Digital 4TB External HDD', 'USB 3.0 portable external hard drive', true, 119.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100010', 'TP-Link Archer AX55 Router', 'AX3000 WiFi 6 dual-band router', true, 129.90, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100011', 'Netgear GS308 Switch', '8-port Gigabit unmanaged switch', true, 29.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100012', 'APC Back-UPS 700VA', 'Uninterruptible power supply with AVR', true, 84.50, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100013', 'Canon PIXMA TR4720', 'All-in-one inkjet printer with WiFi', true, 89.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100014', 'Canon PG-245 Black Ink', 'Standard black ink cartridge', true, 19.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100015', 'Canon CL-246 Color Ink', 'Standard color ink cartridge', true, 24.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100016', 'Apple Magic Trackpad', 'Multi-touch wireless trackpad', true, 129.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100017', 'Apple Magic Keyboard', 'Wireless keyboard with numeric keypad', true, 179.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100018', 'Microsoft Surface Dock 2', 'Docking station with USB-C connectivity', true, 259.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100019', 'Lenovo ThinkPad USB-C Dock Gen 2', 'Universal USB-C docking station', true, 219.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100020', 'Razer DeathAdder V2 Mouse', 'Ergonomic wired gaming mouse 20K DPI', true, 59.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100021', 'Corsair K70 RGB Keyboard', 'Mechanical gaming keyboard with RGB', true, 149.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100022', 'Samsung 27" Odyssey G5', '27-inch QHD 144Hz gaming monitor', true, 279.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100023', 'LG 34" UltraWide Monitor', '34-inch curved IPS monitor', true, 399.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100024', 'Sony WH-1000XM5 Headphones', 'Noise cancelling wireless headphones', true, 349.99, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100025', 'Jabra Evolve2 65 Headset', 'Wireless UC stereo headset with mic', true, 229.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100026', 'Anker PowerCore 20000', '20000mAh portable power bank', true, 49.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100027', 'Belkin 65W USB-C Charger', 'Dual port wall charger PD 3.0', true, 39.95, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100028', 'UGREEN USB-C Hub 6-in-1', 'Multiport adapter with HDMI and USB 3.0', true, 45.00, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100029', 'SanDisk Ultra 128GB USB 3.0', 'USB flash drive 100MB/s', true, 14.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100030', 'SanDisk Extreme 256GB microSD', 'UHS-I U3 memory card with adapter', true, 32.50, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100031', 'GoPro HERO12 Black', '5.3K waterproof action camera', true, 399.99, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100032', 'Nikon D7500 DSLR Camera', '20.9MP DSLR with 18-140mm lens kit', true, 1099.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100033', 'Epson EcoTank ET-2850', 'Supertank color inkjet printer', true, 299.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100034', 'Epson 522 Black Ink Bottle', 'Replacement ink bottle 70ml', true, 16.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100035', 'HP 410X Black Toner', 'High yield LaserJet toner cartridge', true, 119.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100036', 'Xiaomi Mi Smart Plug', 'WiFi smart socket with app control', true, 19.90, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100037', 'Philips Hue White Bulb E27', 'Smart LED bulb 9W Bluetooth', true, 24.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100038', 'TP-Link Tapo C200 Camera', '1080p indoor security camera', true, 34.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100039', 'Ring Video Doorbell 4', 'Battery powered smart doorbell', true, 199.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100040', 'Asus TUF Gaming B550-PLUS', 'ATX motherboard for AMD Ryzen', true, 159.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100041', 'AMD Ryzen 5 5600X', '6-core 12-thread desktop processor', true, 189.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100042', 'Intel Core i7-12700K', '12-core unlocked desktop processor', true, 379.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100043', 'NVIDIA RTX 4060 8GB', 'GDDR6 graphics card PCIe 4.0', true, 329.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100044', 'Cooler Master Hyper 212', 'Air CPU cooler with 120mm fan', true, 39.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100045', 'NZXT H510 Case', 'Mid-tower ATX computer case', true, 89.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100046', 'EVGA 650W Bronze PSU', '80+ Bronze certified power supply', true, 74.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100047', 'LG 55" OLED C3 TV', '55-inch 4K Smart OLED television', true, 1599.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100048', 'Samsung 65" QLED Q70C', '65-inch 4K QLED Smart TV', true, 1199.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100049', 'Bose Solo Soundbar Series II', 'Compact TV soundbar with Bluetooth', true, 199.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100050', 'Amazon Fire TV Stick 4K', 'Streaming media player with Alexa remote', true, 49.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100051', 'Google Chromecast with Google TV', '4K HDR streaming device', true, 49.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100052', 'Dyson V8 Cordless Vacuum', 'Bagless cordless stick vacuum cleaner', true, 349.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100053', 'iRobot Roomba i3', 'Robot vacuum with WiFi connectivity', true, 299.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100054', 'Philips 3000 Series Airfryer', '4.1L digital air fryer', true, 129.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100055', 'Instant Pot Duo 7-in-1 6Qt', 'Electric pressure cooker multi-cooker', true, 99.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100056', 'Tefal OptiGrill+', 'Indoor electric contact grill', true, 179.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100057', 'Panasonic Microwave NN-SN686S', '1200W stainless steel countertop microwave', true, 169.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100058', 'Whirlpool 7kg Front Load Washer', 'Energy efficient washing machine', true, 499.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100059', 'Bosch Series 4 Dishwasher', 'Freestanding 12-place dishwasher', true, 549.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100060', 'DeLonghi EC685 Espresso Machine', '15-bar pump coffee machine', true, 229.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100061', 'Garmin Forerunner 255', 'GPS running smartwatch', true, 349.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100062', 'Fitbit Charge 5', 'Advanced fitness and health tracker', true, 149.95, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100063', 'Samsung Galaxy Tab S9', '11-inch Android tablet 128GB', true, 799.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100064', 'Apple iPad 10th Gen 64GB', '10.9-inch WiFi tablet', true, 449.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100065', 'Lenovo IdeaPad 3 15"', '15.6-inch laptop Ryzen 5 8GB RAM', true, 599.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100066', 'HP Pavilion 14"', '14-inch laptop Intel i5 16GB RAM', true, 749.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100067', 'Acer Aspire 5 17"', '17.3-inch laptop i7 16GB 512GB SSD', true, 899.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100068', 'Dell XPS 13', '13.4-inch premium ultrabook 16GB RAM', true, 1199.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100069', 'MacBook Air M2 13"', 'Apple silicon laptop 256GB SSD', true, 1199.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100070', 'MSI Katana 15 Gaming Laptop', '15.6-inch gaming laptop RTX 4060', true, 1399.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100071', 'PlayStation 5 Console', 'Next-gen gaming console 825GB SSD', true, 499.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100072', 'Xbox Series X', '1TB SSD gaming console', true, 499.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100073', 'Nintendo Switch OLED', '7-inch OLED hybrid console', true, 349.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100074', 'Sony DualSense Controller', 'Wireless controller for PS5', true, 69.99, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100075', 'Xbox Wireless Controller', 'Bluetooth controller for Xbox/PC', true, 59.99, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100076', 'WD Black SN850X 2TB SSD', 'PCIe 4.0 NVMe gaming SSD', true, 179.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100077', 'Crucial MX500 1TB SSD', '2.5-inch SATA solid state drive', true, 79.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100078', 'Synology DS220+ NAS', '2-bay network attached storage', true, 299.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100079', 'QNAP TS-253D', '2-bay NAS with 2.5GbE', true, 369.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100080', 'APC Surge Protector 6-Outlet', 'Power strip with surge protection', true, 24.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100081', 'Brother ADS-1700W Scanner', 'Compact wireless document scanner', true, 299.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100082', 'Fujitsu ScanSnap iX1600', 'High-speed color document scanner', true, 449.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100083', 'Elgato Stream Deck MK.2', '15-key customizable control pad', true, 149.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100084', 'Blue Yeti USB Microphone', 'Condenser microphone for streaming', true, 129.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100085', 'Logitech C920 HD Webcam', '1080p USB webcam with stereo audio', true, 79.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100086', 'TP-Link Deco X20 3-Pack', 'Mesh WiFi 6 system AX1800', true, 249.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100087', 'Ubiquiti UniFi 6 Lite', 'WiFi 6 access point', true, 119.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100088', 'Netatmo Smart Weather Station', 'Indoor and outdoor weather monitor', true, 169.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100089', 'Withings Body+ Scale', 'WiFi smart body scale', true, 99.95, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100090', 'Oral-B iO Series 6', 'Rechargeable electric toothbrush', true, 149.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100091', 'Braun Series 7 Shaver', 'Electric foil shaver with trimmer', true, 129.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100092', 'Philips Series 3000 Trimmer', 'Beard and hair trimmer cordless', true, 39.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100093', 'Eufy RoboVac 11S', 'Slim robotic vacuum cleaner', true, 199.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100094', 'Honeywell HPA300 Air Purifier', 'HEPA air purifier for large rooms', true, 249.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100095', 'Xiaomi Mi Air Purifier 4', 'Smart air purifier with OLED display', true, 199.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100096', 'Toshiba 1TB Canvio Basics', 'Portable external hard drive USB 3.0', true, 54.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100097', 'ADATA 32GB USB Flash Drive', 'USB 3.2 flash drive black', true, 9.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100098', 'Asus ZenScreen 15.6"', 'Portable USB monitor Full HD', true, 249.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100099', 'BenQ PD2705Q Monitor', '27-inch QHD designer monitor', true, 379.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100100', 'LG UltraFine 5K Display', '27-inch 5K IPS monitor Thunderbolt', true, 1299.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100101', 'StarTech USB-C to HDMI Adapter', '4K 60Hz video adapter', true, 29.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100102', 'Anker 7-in-1 USB-C Hub', 'Multiport adapter with Ethernet', true, 59.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100103', 'CyberPower 1500VA UPS', 'Sinewave battery backup system', true, 199.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100104', 'Eaton 5E 850i UPS', '850VA line interactive UPS', true, 109.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100105', 'Ricoh SP 3710DN Printer', 'Mono laser printer with duplex', true, 249.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100106', 'Ricoh SP 3710 Toner', 'Black toner cartridge replacement', true, 79.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100107', 'D-Link DGS-1016D Switch', '16-port Gigabit desktop switch', true, 89.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100108', 'MikroTik hAP ac3', 'Dual-band WiFi router with 5 Gigabit ports', true, 129.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100109', 'Tile Pro 2022', 'Bluetooth item tracker 2-pack', true, 59.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100110', 'Samsung T7 1TB Portable SSD', 'USB 3.2 external solid state drive', true, 99.99, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100111', 'Crucial 32GB DDR5 5600MHz', 'Desktop memory module CL36', true, 129.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100112', 'Gigabyte B760M DS3H', 'Micro-ATX motherboard for Intel 13th Gen', true, 149.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100113', 'Fractal Design Meshify C', 'Mid-tower ATX case with tempered glass', true, 109.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100114', 'Be Quiet! Pure Rock 2', '120mm tower CPU air cooler', true, 44.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100115', 'Seasonic Focus GX-750', '750W 80+ Gold modular PSU', true, 119.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100116', 'Epson WorkForce ES-400 II', 'Duplex document scanner', true, 349.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100117', 'ViewSonic VX2718 Monitor', '27-inch Full HD 165Hz gaming monitor', true, 199.00, 'CAD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100118', 'Motorola Moto G Stylus 2023', 'Android smartphone 128GB storage', true, 249.00, 'USD', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100119', 'Nokia 105 Dual SIM', 'Basic feature phone long battery life', true, 29.99, 'EUR', gen_random_uuid()),
(nextval('orders.product_id_seq'::regclass), 'SKU-100120', 'TP-Link TL-SG1005P', '5-port Gigabit switch with 4 PoE ports', true, 59.99, 'CAD', gen_random_uuid());
COMMIT;

INSERT INTO users.customer_user (id, external_id, username, email, role_id, status_id, created, address_line1, address_line2, "password")
VALUES
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'jdoe', 'jdoe@example.com', 1, 0, now(), '123 Maple Street', 'Apt 4B', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'asmith', 'asmith@example.com', 1, 0, now(), '456 Oak Avenue', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'mbrown', 'mbrown@example.com', 1, 0, now(), '789 Pine Road', 'Suite 2', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'tjohnson', 'tjohnson@example.com', 1, 0, now(), '321 Cedar Lane', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'ewilson', 'ewilson@example.com', 1, 0, now(), '654 Birch Blvd', 'Floor 3', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'dlee', 'dlee@example.com', 1, 0, now(), '987 Spruce Street', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'hwalker', 'hwalker@example.com', 1, 0, now(), '159 Elm Street', 'Unit 12', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'cwhite', 'cwhite@example.com', 1, 0, now(), '753 Willow Drive', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'kgonzalez', 'kgonzalez@example.com', 1, 0, now(), '852 Aspen Court', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'rbaker', 'rbaker@example.com', 1, 0, now(), '951 Poplar Way', 'Apt 8C', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'nmartinez', 'nmartinez@example.com', 1, 0, now(), '147 Cypress Street', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'lrodriguez', 'lrodriguez@example.com', 1, 0, now(), '258 Magnolia Ave', 'Suite 5', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'jhernandez', 'jhernandez@example.com', 1, 0, now(), '369 Palm Street', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'slopez', 'slopez@example.com', 1, 0, now(), '741 Redwood Lane', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'bclark', 'bclark@example.com', 1, 0, now(), '852 Hickory Drive', 'Apt 2A', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'dlewis', 'dlewis@example.com', 1, 0, now(), '963 Walnut Street', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'pscott', 'pscott@example.com', 1, 0, now(), '111 Cherry Lane', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'kgreen', 'kgreen@example.com', 1, 0, now(), '222 Sycamore Ave', 'Unit 7', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'ahall', 'ahall@example.com', 1, 0, now(), '333 Dogwood Drive', '', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2'),
(nextval('users.customer_user_id_seq'::regclass), gen_random_uuid(), 'mallen', 'mallen@example.com', 1, 0, now(), '444 Fir Street', 'Suite 10', '$2a$10$t5FV/DmKq4GbRrckTV7kqe4QSqkrfPAE9sNmF.jKbFsrp0.0dBLx2');
COMMIT;
